server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    username: postgres #edit
    password: myroot #edit
    url: jdbc:postgresql://localhost:5432/identity_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db/changelog/db-changelog-master.xml
    url: jdbc:postgresql://localhost:5432/identity_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    user: postgres #edit
    password: myroot #edit

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
