server:
  port: 8085

spring:
  application:
    name: api-gateway
  jackson:
    default-property-inclusion: non_null
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: food-delivery
          uri: lb://food-delivery
          predicates:
            - Path=/foodDelivery/**
          filters:
            - StripPrefix=1

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1

        - id: restaurant-info-service
          uri: lb://restaurant-info-service
          predicates:
            - Path=/restaurantInfo/**
          filters:
            - StripPrefix=1

        - id: courier-manager
          uri: lb://courier-manager
          predicates:
            - Path=/courierManager/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: secret

