server:
  port: 8080

spring:
  application:
    name: food-delivery
  datasource:
    username: postgres #edit
    password: mnr1209 #edit
    url: jdbc:postgresql://localhost:5432/food_delivery_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db/changelog/db-changelog-master.xml
    url: jdbc:postgresql://localhost:5432/food_delivery_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    user: postgres #edit
    password: mnr1209 #edit

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true