server:
  port: 8080

spring:
  application:
    name: food-delivery
  datasource:
    username: username #edit
    password: password #edit
    url: jdbc:postgresql://localhost:5432/food_delivery_service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true